In [38]:
from sympy.physics.matrices import mgamma
import numpy as np

np.set_printoptions(precision=3, suppress=True)

In [62]:
P0 = np.asarray(mgamma(0))
P1 = 1j*np.asarray(mgamma(1))
P2 = 1j*np.asarray(mgamma(2))
P3 = 1j*np.asarray(mgamma(3))
P5 = np.asarray(mgamma(5))

# P0 = mgamma(0)
# P1 = mgamma(1)
# P2 = mgamma(2)
# P3 = mgamma(3)
# P5 = mgamma(5)

In [64]:
for i in [P0,P1,P2,P3,P5]:
    print(i)
    print(np.dot(i,i))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 -1 0]
 [0 0 0 -1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 0 0 1.0*I]
 [0 0 1.0*I 0]
 [0 -1.0*I 0 0]
 [-1.0*I 0 0 0]]
[[1.00000000000000 0 0 0]
 [0 1.00000000000000 0 0]
 [0 0 1.00000000000000 0]
 [0 0 0 1.00000000000000]]
[[0 0 0 1.00000000000000]
 [0 0 -1.00000000000000 0]
 [0 -1.00000000000000 0 0]
 [1.00000000000000 0 0 0]]
[[1.00000000000000 0 0 0]
 [0 1.00000000000000 0 0]
 [0 0 1.00000000000000 0]
 [0 0 0 1.00000000000000]]
[[0 0 1.0*I 0]
 [0 0 0 -1.0*I]
 [-1.0*I 0 0 0]
 [0 1.0*I 0 0]]
[[1.00000000000000 0 0 0]
 [0 1.00000000000000 0 0]
 [0 0 1.00000000000000 0]
 [0 0 0 1.00000000000000]]
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [61]:
print(np.dot(np.dot(P0, P1), np.dot(P2, P3)))
print(P5)

[[0 0 -1.00000000000000 0]
 [0 0 0 -1.00000000000000]
 [-1.00000000000000 0 0 0]
 [0 -1.00000000000000 0 0]]
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


In [55]:
z = 1j
z*z

(-1+0j)