In [298]:
%matplotlib inline
from syk_susy_2 import *
import numpy as np
from numpy import linalg as LA
import scipy.linalg as SLA
import matplotlib.pyplot as plt
import manipulate
from importlib import reload
reload(manipulate)
import math

In [264]:
def entropy(M):
    w, v = LA.eig(M)
    rho = 0
    for i in w:
        if (i != 0): rho += i*np.log(i)
    return rho

In [205]:
H = hamiltonian(5,1)
w, v = manipulate.eigen(H)
print(w)
# np.dot(v.conj().T, v)
Ha = manipulate.reconstruct(w,v)
np.max(H-Ha)
# print(manipulate.set_zeros(np.dot(H, v[:,20])))
# print(sum(w==0))
# plt.imshow(np.abs(np.dot(v.conj().T, v)), interpolation='nearest', cmap='hot_r')
# plt.colorbar()
# plt.show()

[ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  1.03093563  1.03093563  1.03093563  1.03093563  2.59758764  2.59758764
  2.59758764  2.59758764  3.62852327  3.62852327  3.62852327  3.62852327]
[ 0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.02818593+0.00349974j  0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
  0.00000000+0.j          0.00000000+0.j          0.20718183+0.40176256j
  0.00000000+0.j          0.00000000+0.j          0.00000000+0.j
 -0.04351422+0.14429325j  0.00000000+0.j 

In [299]:
H = hamiltonian(8,1)
w, v = manipulate.eigen(H)
ngs = sum(w==0)
tot_gs = v[0]
for i in range(1,ngs):
    tot_gs += v[i]
tot_gs = tot_gs/math.sqrt(ngs)
for i in range(1,20):
    rho = manipulate.partial_trace(i, tot_gs)
    print("Entropy for trace over %2d psis is %1.6f" % (i,-entropy(rho)))

1.0
Entropy for trace over  1 psis is -0.000000
0.995441576233
Entropy for trace over  2 psis is 0.694431
0.989067535587
Entropy for trace over  3 psis is 1.097307
0.981127167737
Entropy for trace over  4 psis is 1.378471
0.976048507745
Entropy for trace over  5 psis is 1.594058
0.971976708432
Entropy for trace over  6 psis is 1.767512
0.967571393005
Entropy for trace over  7 psis is 1.911569
0.963313424945
Entropy for trace over  8 psis is 2.035169
0.959186021023
Entropy for trace over  9 psis is 2.142150
0.954719940145
Entropy for trace over 10 psis is 2.236066
0.950857868495
Entropy for trace over 11 psis is 2.320488
0.94662712834
Entropy for trace over 12 psis is 2.395820
0.942075887081
Entropy for trace over 13 psis is 2.463151
0.937403848579
Entropy for trace over 14 psis is 2.524072
0.933082018216
Entropy for trace over 15 psis is 2.579826
0.929274439618
Entropy for trace over 16 psis is 2.631921
0.925755386692
Entropy for trace over 17 psis is 2.680559
0.922242454987
Entropy fo

/Users/cstahl/Documents/Junior/Junior Paper II/python/manipulate.py:14: ComplexWarning: Casting complex values to real discards the imaginary part
  rho[i,j] = sum(psi[i:i+N+1]*psi[j:j+N+1].conjucate())


In [54]:
w, v = LA.eig(M)
print(w)

[ 0.64644715+0.j  0.19839705+0.j  0.07157457+0.j  0.08358123+0.j]


In [55]:
L = LA.logm(M)
print(np.trace(np.dot(M,L)))

-0.999112285342


In [56]:
print(sum(w*np.log(w)))

(-0.999112285342+0j)


In [73]:
psi = np.array([0,1,2,3,4,5,6,7,8])
print(partial_trace(9,psi))

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.]
 [  0.   2.   4.   6.   8.  10.  12.  14.  16.]
 [  0.   3.   6.   9.  12.  15.  18.  21.  24.]
 [  0.   4.   8.  12.  16.  20.  24.  28.  32.]
 [  0.   5.  10.  15.  20.  25.  30.  35.  40.]
 [  0.   6.  12.  18.  24.  30.  36.  42.  48.]
 [  0.   7.  14.  21.  28.  35.  42.  49.  56.]
 [  0.   8.  16.  24.  32.  40.  48.  56.  64.]]


In [224]:
M = np.array([[1,0,0],[0,0,0],[0,0,0]])
L = SLA.logm(M)
print(L)

[[  0.           0.           0.        ]
 [  0.         -46.05170186   0.        ]
 [  0.           0.         -46.05170186]]


/Users/cstahl/anaconda3/lib/python3.5/site-packages/scipy/linalg/_matfuncs_inv_ssq.py:830: LogmExactlySingularWarning: The logm input matrix is exactly singular.
  warnings.warn(exact_singularity_msg, LogmExactlySingularWarning)


In [300]:
range(1,5.5)

TypeError: 'float' object cannot be interpreted as an integer