In [1]:
import numpy as np

In [20]:
w = np.asarray([0,1,2,3,4,5,6,7])

In [45]:
def single_trace(rho):
    N = len(rho)
    assert N%2 == 0, "\psi has to have even length"
    M = int(N/2)
    r = np.zeros((M,M))
    for idx in range(M):
        for jdx in range(M):
            r[idx, jdx] = rho[idx, jdx] + rho[idx + N/2, jdx + N/2]
    return r

def partial_trace(rho, traces=1):
    N = len(rho)
    assert N >= 2**traces, "Too many particles to trace over"
    for i in range(traces):
        rho = single_trace(rho)
    return rho

In [46]:
M = np.asarray([w,w+1,w+2,w+3,w+4,w+5,w+6,w+7])
print(partial_trace(M,0))

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [51]:
M = np.asarray([w,w+1,w+2,w+3,w+4,w+5,w+6,w+7])
print(partial_trace(M,3))

[[ 56.]]


/Users/cstahl/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:8: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
