In [1]:
########################################
#  Deprecated. See manipulate.py       #
#  import numpy as np                  #
#  import manipulate                   #
########################################

In [2]:
w = np.asarray([0,1,2,3,4,5,6,7])

In [3]:
def single_trace(rho):
    N = len(rho)
    assert N%2 == 0, "\psi has to have even length"
    M = int(N/2)
    r = np.zeros((M,M))
    for idx in range(M):
        for jdx in range(M):
            r[idx, jdx] = rho[idx, jdx] + rho[idx + M, jdx + M]
    return r

def partial_trace(rho, traces=1):
    N = len(rho)
    assert N >= 2**traces, "Too many particles to trace over"
    for i in range(traces):
        rho = single_trace(rho)
    return rho

In [4]:
M = np.asarray([w,w+1,w+2,w+3,w+4,w+5,w+6,w+7])
print(M)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [7]:
manipulate.partial_trace(M,2)

array([[ 24.,  28.],
       [ 28.,  32.]])