In [1]:
#######################################################
# Deprecated                                          #
# See syk_susy_2.py                                   #
#######################################################

# import numpy as np

# Given $N$ Majorana Fermions

$\left|\phi\right\rangle=\left|\alpha_0\alpha_1\dots\alpha_N\dots\alpha_{2N}\right\rangle,$

$|10100\rangle = \psi_2^\dagger\psi_4^\dagger|0\rangle%$

$\psi_0$ lowers the zeroth fermion in this document, little endian. Elsewhere index by 1, big endian.

In [2]:
def anti_com(a,b):
    return np.dot(a,b)+np.dot(b,a)

def Fermi(n,j):
    F = 0
    for i in np.arange(0,j):
        if (n&2**i) != 0: F += 1
    return F

def psi(N,j):
    assert N%1 == 0, "N must be an integer"
    assert j%1 == 0, "j must be an integer"
    assert j<N, "j must be less than N"
    assert N>=0, "N must be greater than or equal to 0"
    assert j>=0, "j must be greater than or equal to 0"
    k = np.floor(j/2)
    psi = np.zeros((2**N,2**N))
    for n, row in enumerate(psi):
        for m, elem in enumerate(row):
            if (n-m == 2**j) and (n&2**j != 0) and (m&2**j == 0): 
                psi[m,n] = (-1)**Fermi(n,j)
    return psi

def psi_dag(N,j):
    assert N%1 == 0, "N must be an integer"
    assert j%1 == 0, "j must be an integer"
    assert j<N, "j must be less than N"
    assert j>=0, "j must be greater than or equal to 0"
    psi = np.zeros((2**N,2**N))
    for m, row in enumerate(psi):
        for n, elem in enumerate(row):
            if   (m-n == 2**j) and (n&2**j == 0) and (m&2**j != 0): 
                psi[m,n] = (-1)**Fermi(n,j)
    return psi

Two matrices A, B are equal `iff np.any(A-B) == False`

In [3]:
def check(N):
    assert N%1 == 0, "N must be an integer"
    assert N>=0, "N must be greater than or equal to 0"
    for j in np.arange(N):
        psi_j = psi(N,j)
        psi_dag_j = psi_dag(N,j)
        for i in np.arange(N):
            psi_i = psi(N,i)
            acom = anti_com(psi_j, psi_i)
            if np.any(acom): return(0, "{psi(%d,%d), psi(%d,%d)} \ne 0" % (N,j,N,i))
            psi_dag_i = psi_dag(N,i)
            acom = anti_com(psi_dag_j, psi_dag_i)
            if np.any(acom): return(0, "{psi_dag(%d,%d), psi_dag(%d,%d)} \ne 0" % (N,j,N,i))
            acom = anti_com(psi_j, psi_dag_i)
            if i == j:
                if np.any(acom - np.eye(2**N)): return(0, "{psi(%d,%d), psi_dag(%d,%d)} \ne 1" % (N,j,N,i))
            else: 
                if np.any(acom): return(0, "{psi(%d,%d), psi_dag(%d,%d)} \ne 0" % (N,j,N,i))
    return(1, "good")

In [80]:
print(psi_dag(1,0),'\n')
print(psi_dag(2,1),'\n')
print(psi_dag(3,2),'\n')
print(psi_dag(4,2),'\n')
print(psi_dag(5,2),'\n')


[[ 0.  0.]
 [ 1.  0.]] 

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]] 

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 

In [84]:
b = np.zeros((2,2), dtype=complex)
c = np.zeros((2,2), dtype=complex)
b[0,0] = 1j
print(c)
print(b)
print(c+b)

[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]


In [84]:
for i in np.arange(10): 
    if i == 5: continue
    print(i)

0
1
2
3
4
6
7
8
9


In [100]:
if 1==0: assert 0==1

In [4]:
check(5)

(1, 'good')

In [75]:
print(psi(2,1) == psi(2,1))
print(type(psi(2,1)))
print(np.all([psi(2,1)+psi(2,0) == psi(2,1)]))
print(type(np.asarray([[2,1],[1,3]])))
print(np.all([np.asarray([[2,1],[1,3]]), np.asarray([[2,1],[1,3]])]))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
<class 'numpy.ndarray'>
False
<class 'numpy.ndarray'>
True


In [71]:
for (a,b) in np.zeros((4,4)): print('hi')

ValueError: too many values to unpack (expected 2)

In [24]:
ps = np.zeros((4,4))
ps[1,0] = 1

print(ps)

[[ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
