In [1]:
import numpy as np 

In [2]:
sig_1 = np.asarray([[0,  1],[1, 0]])
sig_2 = np.asarray([[0,-1j],[1j,0]])
sig_3 = np.asarray([[1,  0],[0,-1]])
ident = np.asarray([[1,  0],[0, 1]])

In [14]:
def anti_com(a,b):
    return np.dot(a,b)+np.dot(b,a)

def printreal(a):
    for idx, elem in np.ndindex(a):
        assert(np.imag(elem)==0), "only rprint() real arrays"
        a[idx] = np.real(elem)
    
def isreal(a):
    if np.ndim(a)==0: return False
    for idx, elem in np.nditer(a):
        if not np.isclose(np.imag(elem), 0): return False
    return True

def rprint(*args):
    for a in args:
        if isreal(a): a = printreal(a)
    print(args)

# Given $d$ Majorana Fermions,
and $\frac{d}{2}$ Dirac Fermions if $d$ is even,
then the matrices are $N\times N$, where $N=2^{d/2}$.

$\left\lbrace\gamma ^{\mu }\gamma ^{\nu }\right\rbrace=2\eta^{\mu \nu }\,$

$\left|\phi\right\rangle=\left|\alpha_0\alpha_1\dots\alpha_N\dots\alpha_{2N}\right\rangle$  ??

Notes: $\texttt{np.dot()}$ does work how you would expect
###### Indexing starts at 1

In [15]:
def psi(d,i):
    assert d%1==0, "d must be an integer"
    assert i%1==0, "i must be an integer"
    assert d>1, "dimension must be 2 or greater"
    assert i > 0 and i < d+1, "i must be in [1...d]"
    if d == 2:
        if i == 1: return  sig_1
        if i == 2: return  -1j*sig_2
        else: assert 0
    if d == 3:
        if i == 3: return np.asarray([[1j,0],[0,-1j]])
        else: return psi(2,i)
    if (d%2) == 0:
        if i == d-1: return np.kron(np.eye(d-2, dtype="int"), 1j*sig_1)
        if i == d  : return np.kron(np.eye(d-2, dtype="int"), 1j*sig_2)
        else: return np.kron(psi(d-2,i), sig_3)
        #else: return np.kron(psi(d-2,i), sig_3)
    if (d%2) == 1:
        if i == d  : return np.kron(psi(d-2,i-2),sig_3)
        else: return psi(d-1,i)
    assert 0

In [21]:
d = 4

for i in np.arange(1,d+1):
    print(i)
    print(psi(d,i))
    print('\n')

1
[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]


2
[[ 0.+0.j  0.+0.j -1.+0.j -0.+0.j]
 [ 0.+0.j  0.+0.j -0.+0.j  1.-0.j]
 [ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]]


3
[[ 0.+0.j  0.+1.j  0.+0.j  0.+0.j]
 [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]]


4
[[ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [-1.+0.j  0.+0.j -0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [-0.+0.j  0.+0.j -1.+0.j  0.+0.j]]




In [44]:
d = 6
i = 6
N = int(2**np.floor(d/2))

print(psi(d,i))
print("\n{psi^i,psi^i}")
print(anti_com(psi(d,i),psi(d,i)))
print("\n{psi^i,psi^j}")
if d==i: print(anti_com(psi(d,i),psi(d,i-1)))
else:    print(anti_com(psi(d,i),psi(d,i+1)))

[[ 0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [-1.+0.j  0.+0.j -0.+0.j  0.+0.j -0.+0.j  0.+0.j -0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [-0.+0.j  0.+0.j -1.+0.j  0.+0.j -0.+0.j  0.+0.j -0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [-0.+0.j  0.+0.j -0.+0.j  0.+0.j -1.+0.j  0.+0.j -0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [-0.+0.j  0.+0.j -0.+0.j  0.+0.j -0.+0.j  0.+0.j -1.+0.j  0.+0.j]]

{psi^i,psi^i}
[[-2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j -2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+

### d = 5
N = int(2**np.floor(d/2))

psi0 = psi(d,1)
psi1 = psi(d,2)
psi2 = psi(d,3)
psi3 = psi(d,4)

psi4 = np.dot(np.dot(psi0,psi1), np.dot(psi2,psi3))
psi4 = psi(d,4)

print(psi4)
print(np.isclose(anti_com(psi4,psi4),2*np.eye(N)))
for p in [psi0,psi1,psi2,psi3]:
    print(p)
    print(np.isclose(anti_com(psi4,p), np.zeros((N,N))))

In [51]:
d = 4
N = int(2**np.floor(d/2))
p = np.zeros((d+1,N,N), dtype="int")

p[1] = psi(d,1)
p[2] = psi(d,2)
pc = p[1]
for i in np.arange(2,d+1):
    pc = np.dot(pc,p[i])
#print(np.dot(pc,pc))
print(np.dot(np.dot(p[1],p[2]),np.dot(p[3],p[4])), '\n')

for i in np.arange(1,d+1):
    print(anti_com(pc,p[i]))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [129]:
np.isarray(2)

AttributeError: module 'numpy' has no attribute 'isarray'

In [ ]:
clear(psi)

In [85]:
np.asarray([1j*1j])

array([-1.+0.j])

In [118]:
a = np.asarray([[0,0],[0,0]])
b = np.copy(a)
b[0,0] = 1
print(b)
for idx, elem in np.ndenumerate(b): 
    a[idx] = elem
    print(idx, elem)
    
print(a)

[[1 0]
 [0 0]]
(0, 0) 1
(0, 1) 0
(1, 0) 0
(1, 1) 0
[[1 0]
 [0 0]]


In [13]:
np.ndim(1)

0